package learning

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i hw4/internal/group.RepoGroup -o ../learning/repo_mock_g_test.go -n RepoGroupMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RepoGroupMock implements group.RepoGroup
type RepoGroupMock struct {
	t minimock.Tester

	funcSubjects          func() (sa1 []string)
	inspectFuncSubjects   func()
	afterSubjectsCounter  uint64
	beforeSubjectsCounter uint64
	SubjectsMock          mRepoGroupMockSubjects

	funcTutorsID          func(subject string) (ia1 []int64)
	inspectFuncTutorsID   func(subject string)
	afterTutorsIDCounter  uint64
	beforeTutorsIDCounter uint64
	TutorsIDMock          mRepoGroupMockTutorsID
}

// NewRepoGroupMock returns a mock for group.RepoGroup
func NewRepoGroupMock(t minimock.Tester) *RepoGroupMock {
	m := &RepoGroupMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SubjectsMock = mRepoGroupMockSubjects{mock: m}

	m.TutorsIDMock = mRepoGroupMockTutorsID{mock: m}
	m.TutorsIDMock.callArgs = []*RepoGroupMockTutorsIDParams{}

	return m
}

type mRepoGroupMockSubjects struct {
	mock               *RepoGroupMock
	defaultExpectation *RepoGroupMockSubjectsExpectation
	expectations       []*RepoGroupMockSubjectsExpectation
}

// RepoGroupMockSubjectsExpectation specifies expectation struct of the RepoGroup.Subjects
type RepoGroupMockSubjectsExpectation struct {
	mock *RepoGroupMock

	results *RepoGroupMockSubjectsResults
	Counter uint64
}

// RepoGroupMockSubjectsResults contains results of the RepoGroup.Subjects
type RepoGroupMockSubjectsResults struct {
	sa1 []string
}

// Expect sets up expected params for RepoGroup.Subjects
func (mmSubjects *mRepoGroupMockSubjects) Expect() *mRepoGroupMockSubjects {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("RepoGroupMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &RepoGroupMockSubjectsExpectation{}
	}

	return mmSubjects
}

// Inspect accepts an inspector function that has same arguments as the RepoGroup.Subjects
func (mmSubjects *mRepoGroupMockSubjects) Inspect(f func()) *mRepoGroupMockSubjects {
	if mmSubjects.mock.inspectFuncSubjects != nil {
		mmSubjects.mock.t.Fatalf("Inspect function is already set for RepoGroupMock.Subjects")
	}

	mmSubjects.mock.inspectFuncSubjects = f

	return mmSubjects
}

// Return sets up results that will be returned by RepoGroup.Subjects
func (mmSubjects *mRepoGroupMockSubjects) Return(sa1 []string) *RepoGroupMock {
	if mmSubjects.mock.funcSubjects != nil {
		mmSubjects.mock.t.Fatalf("RepoGroupMock.Subjects mock is already set by Set")
	}

	if mmSubjects.defaultExpectation == nil {
		mmSubjects.defaultExpectation = &RepoGroupMockSubjectsExpectation{mock: mmSubjects.mock}
	}
	mmSubjects.defaultExpectation.results = &RepoGroupMockSubjectsResults{sa1}
	return mmSubjects.mock
}

// Set uses given function f to mock the RepoGroup.Subjects method
func (mmSubjects *mRepoGroupMockSubjects) Set(f func() (sa1 []string)) *RepoGroupMock {
	if mmSubjects.defaultExpectation != nil {
		mmSubjects.mock.t.Fatalf("Default expectation is already set for the RepoGroup.Subjects method")
	}

	if len(mmSubjects.expectations) > 0 {
		mmSubjects.mock.t.Fatalf("Some expectations are already set for the RepoGroup.Subjects method")
	}

	mmSubjects.mock.funcSubjects = f
	return mmSubjects.mock
}

// Subjects implements group.RepoGroup
func (mmSubjects *RepoGroupMock) Subjects() (sa1 []string) {
	mm_atomic.AddUint64(&mmSubjects.beforeSubjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmSubjects.afterSubjectsCounter, 1)

	if mmSubjects.inspectFuncSubjects != nil {
		mmSubjects.inspectFuncSubjects()
	}

	if mmSubjects.SubjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSubjects.SubjectsMock.defaultExpectation.Counter, 1)

		mm_results := mmSubjects.SubjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmSubjects.t.Fatal("No results are set for the RepoGroupMock.Subjects")
		}
		return (*mm_results).sa1
	}
	if mmSubjects.funcSubjects != nil {
		return mmSubjects.funcSubjects()
	}
	mmSubjects.t.Fatalf("Unexpected call to RepoGroupMock.Subjects.")
	return
}

// SubjectsAfterCounter returns a count of finished RepoGroupMock.Subjects invocations
func (mmSubjects *RepoGroupMock) SubjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.afterSubjectsCounter)
}

// SubjectsBeforeCounter returns a count of RepoGroupMock.Subjects invocations
func (mmSubjects *RepoGroupMock) SubjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSubjects.beforeSubjectsCounter)
}

// MinimockSubjectsDone returns true if the count of the Subjects invocations corresponds
// the number of defined expectations
func (m *RepoGroupMock) MinimockSubjectsDone() bool {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		return false
	}
	return true
}

// MinimockSubjectsInspect logs each unmet expectation
func (m *RepoGroupMock) MinimockSubjectsInspect() {
	for _, e := range m.SubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to RepoGroupMock.Subjects")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to RepoGroupMock.Subjects")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSubjects != nil && mm_atomic.LoadUint64(&m.afterSubjectsCounter) < 1 {
		m.t.Error("Expected call to RepoGroupMock.Subjects")
	}
}

type mRepoGroupMockTutorsID struct {
	mock               *RepoGroupMock
	defaultExpectation *RepoGroupMockTutorsIDExpectation
	expectations       []*RepoGroupMockTutorsIDExpectation

	callArgs []*RepoGroupMockTutorsIDParams
	mutex    sync.RWMutex
}

// RepoGroupMockTutorsIDExpectation specifies expectation struct of the RepoGroup.TutorsID
type RepoGroupMockTutorsIDExpectation struct {
	mock    *RepoGroupMock
	params  *RepoGroupMockTutorsIDParams
	results *RepoGroupMockTutorsIDResults
	Counter uint64
}

// RepoGroupMockTutorsIDParams contains parameters of the RepoGroup.TutorsID
type RepoGroupMockTutorsIDParams struct {
	subject string
}

// RepoGroupMockTutorsIDResults contains results of the RepoGroup.TutorsID
type RepoGroupMockTutorsIDResults struct {
	ia1 []int64
}

// Expect sets up expected params for RepoGroup.TutorsID
func (mmTutorsID *mRepoGroupMockTutorsID) Expect(subject string) *mRepoGroupMockTutorsID {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("RepoGroupMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &RepoGroupMockTutorsIDExpectation{}
	}

	mmTutorsID.defaultExpectation.params = &RepoGroupMockTutorsIDParams{subject}
	for _, e := range mmTutorsID.expectations {
		if minimock.Equal(e.params, mmTutorsID.defaultExpectation.params) {
			mmTutorsID.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmTutorsID.defaultExpectation.params)
		}
	}

	return mmTutorsID
}

// Inspect accepts an inspector function that has same arguments as the RepoGroup.TutorsID
func (mmTutorsID *mRepoGroupMockTutorsID) Inspect(f func(subject string)) *mRepoGroupMockTutorsID {
	if mmTutorsID.mock.inspectFuncTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("Inspect function is already set for RepoGroupMock.TutorsID")
	}

	mmTutorsID.mock.inspectFuncTutorsID = f

	return mmTutorsID
}

// Return sets up results that will be returned by RepoGroup.TutorsID
func (mmTutorsID *mRepoGroupMockTutorsID) Return(ia1 []int64) *RepoGroupMock {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("RepoGroupMock.TutorsID mock is already set by Set")
	}

	if mmTutorsID.defaultExpectation == nil {
		mmTutorsID.defaultExpectation = &RepoGroupMockTutorsIDExpectation{mock: mmTutorsID.mock}
	}
	mmTutorsID.defaultExpectation.results = &RepoGroupMockTutorsIDResults{ia1}
	return mmTutorsID.mock
}

// Set uses given function f to mock the RepoGroup.TutorsID method
func (mmTutorsID *mRepoGroupMockTutorsID) Set(f func(subject string) (ia1 []int64)) *RepoGroupMock {
	if mmTutorsID.defaultExpectation != nil {
		mmTutorsID.mock.t.Fatalf("Default expectation is already set for the RepoGroup.TutorsID method")
	}

	if len(mmTutorsID.expectations) > 0 {
		mmTutorsID.mock.t.Fatalf("Some expectations are already set for the RepoGroup.TutorsID method")
	}

	mmTutorsID.mock.funcTutorsID = f
	return mmTutorsID.mock
}

// When sets expectation for the RepoGroup.TutorsID which will trigger the result defined by the following
// Then helper
func (mmTutorsID *mRepoGroupMockTutorsID) When(subject string) *RepoGroupMockTutorsIDExpectation {
	if mmTutorsID.mock.funcTutorsID != nil {
		mmTutorsID.mock.t.Fatalf("RepoGroupMock.TutorsID mock is already set by Set")
	}

	expectation := &RepoGroupMockTutorsIDExpectation{
		mock:   mmTutorsID.mock,
		params: &RepoGroupMockTutorsIDParams{subject},
	}
	mmTutorsID.expectations = append(mmTutorsID.expectations, expectation)
	return expectation
}

// Then sets up RepoGroup.TutorsID return parameters for the expectation previously defined by the When method
func (e *RepoGroupMockTutorsIDExpectation) Then(ia1 []int64) *RepoGroupMock {
	e.results = &RepoGroupMockTutorsIDResults{ia1}
	return e.mock
}

// TutorsID implements group.RepoGroup
func (mmTutorsID *RepoGroupMock) TutorsID(subject string) (ia1 []int64) {
	mm_atomic.AddUint64(&mmTutorsID.beforeTutorsIDCounter, 1)
	defer mm_atomic.AddUint64(&mmTutorsID.afterTutorsIDCounter, 1)

	if mmTutorsID.inspectFuncTutorsID != nil {
		mmTutorsID.inspectFuncTutorsID(subject)
	}

	mm_params := &RepoGroupMockTutorsIDParams{subject}

	// Record call args
	mmTutorsID.TutorsIDMock.mutex.Lock()
	mmTutorsID.TutorsIDMock.callArgs = append(mmTutorsID.TutorsIDMock.callArgs, mm_params)
	mmTutorsID.TutorsIDMock.mutex.Unlock()

	for _, e := range mmTutorsID.TutorsIDMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ia1
		}
	}

	if mmTutorsID.TutorsIDMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmTutorsID.TutorsIDMock.defaultExpectation.Counter, 1)
		mm_want := mmTutorsID.TutorsIDMock.defaultExpectation.params
		mm_got := RepoGroupMockTutorsIDParams{subject}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmTutorsID.t.Errorf("RepoGroupMock.TutorsID got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmTutorsID.TutorsIDMock.defaultExpectation.results
		if mm_results == nil {
			mmTutorsID.t.Fatal("No results are set for the RepoGroupMock.TutorsID")
		}
		return (*mm_results).ia1
	}
	if mmTutorsID.funcTutorsID != nil {
		return mmTutorsID.funcTutorsID(subject)
	}
	mmTutorsID.t.Fatalf("Unexpected call to RepoGroupMock.TutorsID. %v", subject)
	return
}

// TutorsIDAfterCounter returns a count of finished RepoGroupMock.TutorsID invocations
func (mmTutorsID *RepoGroupMock) TutorsIDAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.afterTutorsIDCounter)
}

// TutorsIDBeforeCounter returns a count of RepoGroupMock.TutorsID invocations
func (mmTutorsID *RepoGroupMock) TutorsIDBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmTutorsID.beforeTutorsIDCounter)
}

// Calls returns a list of arguments used in each call to RepoGroupMock.TutorsID.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmTutorsID *mRepoGroupMockTutorsID) Calls() []*RepoGroupMockTutorsIDParams {
	mmTutorsID.mutex.RLock()

	argCopy := make([]*RepoGroupMockTutorsIDParams, len(mmTutorsID.callArgs))
	copy(argCopy, mmTutorsID.callArgs)

	mmTutorsID.mutex.RUnlock()

	return argCopy
}

// MinimockTutorsIDDone returns true if the count of the TutorsID invocations corresponds
// the number of defined expectations
func (m *RepoGroupMock) MinimockTutorsIDDone() bool {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		return false
	}
	return true
}

// MinimockTutorsIDInspect logs each unmet expectation
func (m *RepoGroupMock) MinimockTutorsIDInspect() {
	for _, e := range m.TutorsIDMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoGroupMock.TutorsID with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.TutorsIDMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		if m.TutorsIDMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoGroupMock.TutorsID")
		} else {
			m.t.Errorf("Expected call to RepoGroupMock.TutorsID with params: %#v", *m.TutorsIDMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcTutorsID != nil && mm_atomic.LoadUint64(&m.afterTutorsIDCounter) < 1 {
		m.t.Error("Expected call to RepoGroupMock.TutorsID")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepoGroupMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSubjectsInspect()

		m.MinimockTutorsIDInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepoGroupMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepoGroupMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSubjectsDone() &&
		m.MinimockTutorsIDDone()
}
